### ISSUE TITLE
How to make it non HTTPS?

### ISSUE THREAD

**Issue by svsa** [andershedstrom/openshift-community-artifactory#2]
This is almost exactly what we want, but I would prefer to not have it running https!

Is that an easy change for us to make?

(I couldn't find where else to leave this question, sorry!)

**Comment by andershedstrom** [comment]
You would need to update `metadata/manifest.yml` and remove the redirect to https `Options: {tohttps: true}`

Sorry about the reaaaaaally late reply, but....better late than never...
